apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: latency
        role: rolling-update
    spec:
      containers:
      - name: latency-container
        image: gcr.io/hbl-poc-enterprisefac-pm-prj/asia-south1/latency/springbootlatency:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /fundservice/actuator/health
            port: 8080
            scheme: HTTP
  strategy:
    type: RollingUpdate
     maxSurge: 25%
     maxUnavailable: 1
